---
- name: Install epel release
  yum:
    name: epel-release
    state: present

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Install yum-utils
  yum:
    name: yum-plugin-fastestmirror

- name: Install Remi Repo.
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: enable remi-php72
  shell: yum-config-manager --enable remi-php72

- name: Install PHP 7.2
  yum:
   name:
    - php
    - php-fpm
    - php-common
    - php-pear
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-pspell
    - php-gd
    - php-curl
    - php-pecl-memcached
    - php-mysql
    - php-ldap
    - php-zip
    - php-fileinfo
    - php-xml
    - php-intl
    - php-pecl-memcache
    - php-readline
    - php-mbstring
    - php-xmlrpc
    - php-soap
    - php-pdo
    - php-pgsql
    - php-pecl-apcu
    - php-json
   state: latest
   update_cache: yes

- name: Changing config php.ini №
  replace:
    path: /etc/php.ini
    regexp: ';cgi.fix_pathinfo=1'
    replace: 'cgi.fix_pathinfo=0'
 
- name: Changing config PHP
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: 'listen = 127.0.0.1:9000'
    replace: 'listen = /var/run/php-fpm/php-fpm.sock'

- name: Changing config PHP 10 %
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: ';listen.owner = nobody'
    replace: 'listen.owner = nginx'

- name: Changing config PHP 20 %
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: ';listen.group = nobody'
    replace: 'listen.group = nginx'

- name: Changing config PHP 40 %
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: 'user = apache'
    replace: 'user = nginx'

- name: Changing config PHP 50 %
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: 'group = apache'
    replace: 'group = nginx'

- name: Changing config PHP 60%
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: ';listen.mode = 0660'
    replace: 'listen.mode = 0660'

- name: Changing config PHP 80%
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: ';env'
    replace: 'env'

- name: Changing config PHP 100%
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: ';security.limit_extensions = .php .php3 .php4 .php5 .php7'
    replace: 'security.limit_extensions = .php'

- name: Create a new directory for the php session path
  file:
    path: /var/lib/php/session/
    state: directory
    owner: nginx
    group: nginx

- name: Install required SELinux management tools
  yum:
    name: policycoreutils-python
    state: present

- name: Creates directory /var/moodledata
  file:
    path: /var/moodledata
    state: directory
    owner: nginx
    group: nginx

- name: Changing SElinux policy to run in permissive mode for Nginx
  command: semanage permissive -a httpd_t

- name: Start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: Creates directory
  file:
    path: /temp
    state: directory
    
- name: Extract moodle-latest-36.tgz into /temp
  unarchive:
    src: https://download.moodle.org/download.php/direct/stable36/moodle-latest-36.tgz
    dest: /temp
    owner: nginx
    group: nginx
    remote_src: yes

- name: Remove Nginx root
  file:
    path: /var/www/html
    state: absent

- name: Move Moodle dir to Nginx root
  shell: mv /temp/moodle /var/www/html

- name: Configure a virtual host for Moodle
  template: src=/home/vagrant/provision/templates/moodle.cfg.j2 dest=/etc/nginx/conf.d/moodle.conf

- name: Add WEB Host IP
  replace:
    path: /etc/nginx/conf.d/moodle.conf
    regexp: 'paste_here_ip_of_web'
    replace: '{{web_ip}}'

- name: Configure a virtual host
  template: src=/home/vagrant/provision/templates/nginx.cfg.j2 dest=/etc/nginx/nginx.conf

- name: Install Moodle
  command: php /var/www/html/admin/cli/install.php 
     --skip-database 
     --lang=uk 
     --chmod=2777 
     --wwwroot=http://{{web_ip}}:80 
     --dataroot=/var/moodledata 
     --dbtype=pgsql 
     --dbhost={{db_ip}} 
     --dbname={{base_name}} 
     --dbport={{db_port}} 
     --dbuser={{db_user}} 
     --dbpass={{db_pass}} 
     --fullname=Moodle 
     --shortname=MD 
     --summary=Moodle 
     --adminuser={{moodle_user}} 
     --adminpass={{moodle_pass}} 
     --non-interactive 
     --agree-license

- file:
    path: /var/www/html/config.php
    state: touch
    mode: "o+r"

- name: Restart service php-fpm
  service:
    name: php-fpm
    state: restarted

- name: Restart service Nginx
  service:
    name: nginx
    state: restarted
...