---
- hosts: ALL_VM
  become: true
  tasks:
    - include: /home/vagrant/provision/ansible_playbooks/pb_all.yml

- hosts: DB_VM
  become: true
  tasks:
    - name: Copy Var file
      template: src=/home/vagrant/provision/variables/global_vars.sh dest=/home/vagrant/global_vars.sh
    - name: Configure PostgreSQL Access List
      template: src=/home/vagrant/provision/templates/postgre_access_vars.cfg dest=/home/vagrant/postgre_access_vars.cfg
    - script: /home/vagrant/provision/shell_script/scenario_1.sh
...