- hosts: Task4_3
  become: true
  
- name: Virtual Host Permisions
  tasks:
     file: dest=/var/www/html
     owner: nginx
     group: nginx
     mode: u=rwX,g=rX,o=rX
     recurse: yes

- name: Virtual Host Permisions
  tasks:
     file: dest=/var/moodledata
     owner: nginx
     group: nginx
     mode: u=rwX,g=rX,o=rX
     recurse: yes