# -*- mode: ruby -*- 
# vi: set ft=ruby : 
# Every Vagrant development environment requires a box. You can search for 
# boxes at https://atlas.hashicorp.com/search. 
BOX_IMAGE = "centos/7" 
MACINES_COUNT = 4
MACINES_NAME = "Task3" # For Name will be added count 
IP_PART1 = 192
IP_PART2 = 168
IP_PART3 = 56
IP_PART4 = 10 #Next machines addresses will be + (i)

Vagrant.configure("2") do |config|
  (1..MACINES_COUNT).each do |i|
    config.vm.define "#{MACINES_NAME}_#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE 
      subconfig.vm.hostname = "#{MACINES_NAME}#{i}"
      subconfig.vm.network :private_network, ip: "#{IP_PART1}.#{IP_PART2}.#{IP_PART3}.#{IP_PART4 - 1 + i}"
      subconfig.vm.provision "shell", path: "scenario_#{i}.sh"
  end
end 
end 
